# **Problem** : This is a Real World Data set from a European Natural Gas Powerplant.The data set contains Various features which affect the Power Output(PE).I still don't understand how the features affect the Power Output (Im not a Physicist) needless to say we can still predict the Power output using our various Wonderful Regression ML Techniques  

Note : Although the given type of problem is generally Complicated and require a lot of Preliminary & Exploratory Analysis and As well as intense Data Cleaning. But our Aim is to Explore and Compare the Accuracy of Mutiple Regression ML Techniques , therefore we will Prioritise the Comparison b/w models over the EDA and Data Cleaning. To do this I chose a much Simpler and Ready to use dataset from UCI Machine Learning Repositary.

**1.Importing the Libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**2.Importing the DataSet**

In [2]:
df = pd.read_csv('Data.csv')

**3.Preliminary Analysis and Missing value Detection & Rectification**

In [3]:
df.shape

(9568, 5)

In [4]:
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [5]:
df.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [6]:
df.columns

Index(['AT', 'V', 'AP', 'RH', 'PE'], dtype='object')

**4.Splitting the Dataset**

Splitting the dataset into Dependent and Independent variables

In [7]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

Splitting the dataset into Train set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# **5.Training the Model Using Various Regression ML Techniques**

**a. Multiple Linear Regression**

In [9]:
from sklearn.linear_model import LinearRegression
regressor1 = LinearRegression()
regressor1.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
y_pred1 = regressor1.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test.reshape(len(y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


In [11]:
from sklearn.metrics import r2_score
a1 = r2_score(y_test, y_pred1)
print(a1)

0.9325315554761302


**b. Polynomial Regression**

In [12]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor2 = LinearRegression()
regressor2.fit(X_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
y_pred2 = regressor2.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


In [14]:
from sklearn.metrics import r2_score
a2 = r2_score(y_test, y_pred2)
print(a2)

0.9458192606428238


**c. Decision Tree Regression**

In [15]:
from sklearn.tree import DecisionTreeRegressor
regressor3 = DecisionTreeRegressor(random_state = 0)
regressor3.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

In [16]:
y_pred3 = regressor3.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred3.reshape(len(y_pred3),1), y_test.reshape(len(y_test),1)),1))

[[431.28 431.23]
 [462.81 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.55 463.28]]


In [17]:
from sklearn.metrics import r2_score
a3 = r2_score(y_test, y_pred3)
print(a3)

0.9226091050550043


**d. Random Forest Regression**

In [18]:
from sklearn.ensemble import RandomForestRegressor
regressor4 = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor4.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [19]:
y_pred4 = regressor4.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred4.reshape(len(y_pred4),1), y_test.reshape(len(y_test),1)),1))

[[433.78 431.23]
 [457.99 460.01]
 [463.14 461.14]
 ...
 [470.16 473.26]
 [439.51 438.  ]
 [460.32 463.28]]


In [20]:
from sklearn.metrics import r2_score
a4 = r2_score(y_test, y_pred4)
print(a4)

0.9615980699813017


**e. Support Vector Regression**

Note : All the Previous ML-Regression Techniques donot compulsarily need Feature Scaling (Although it is done to avoid the Outliers).SVR compulsarily needs Feature Scaling to function Effectively. This is because of the way this Technique is Formulated.

In [21]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = pd.DataFrame(y_train)
y_train = sc_y.fit_transform(y_train)

In [22]:
from sklearn.svm import SVR
regressor5 = SVR(kernel = 'rbf')
regressor5.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [23]:
y_pred5 = sc_y.inverse_transform(regressor5.predict(sc_X.transform(X_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred5.reshape(len(y_pred5),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


In [24]:
from sklearn.metrics import r2_score
a5 = r2_score(y_test, y_pred5)
print(a5)

0.9480784049986258


# **6.Aggregation of the Results**

In [25]:
print('Regression Technique','       | ','R2 Square Value')
print('Multiple Linear Regression',' : ',a1)
print('Polynomial Regression',' :      ',a2)
print('Decision Tree Regression',' :   ',a3)
print('Random Forest Regression',' :   ',a4)
print('Support Vector Regression',' :  ',a5)

Regression Technique        |  R2 Square Value
Multiple Linear Regression  :  0.9325315554761302
Polynomial Regression  :       0.9458192606428238
Decision Tree Regression  :    0.9226091050550043
Random Forest Regression  :    0.9615980699813017
Support Vector Regression  :   0.9480784049986258


**As you can see from above Random Forest Regression has the highest R2 Value . Which is no fluke . Generally Random Forest and Supprt Vector Regression always give very good predictions.**