<a href="https://colab.research.google.com/github/Nirmalkumar1911/IndepVAR/blob/main/Telcom_Customer_Churn_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Churn Modelling using Artificial Neural Network



**1.Importing Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

**2.Importing Data and Exploratory Data Analysis**

In [2]:
dataset = pd.read_excel('Telco-Customer-Churn.xlsx')
dataset.head()

customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [4]:
dataset.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [5]:
dataset.shape

(7043, 21)

**3.Seperating the Dependent and Independent Variables**

In [6]:
# Since the Customer Id is unnessecary for prediction we can just Ignore it #
x = dataset.iloc[:,1:-1]
x.iloc[:2,:]

gender  SeniorCitizen Partner  ...     PaymentMethod  MonthlyCharges TotalCharges
0  Female              0     Yes  ...  Electronic check           29.85        29.85
1    Male              0      No  ...      Mailed check           56.95       1889.5

[2 rows x 19 columns]

In [7]:
y = dataset.iloc[:,-1].values
y[:10]

array(['No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'],
      dtype=object)

**4.Encoding the Categorical Variables**

In [8]:
from sklearn.preprocessing import LabelEncoder
cols = ['gender','Partner','Dependents','PhoneService','PaperlessBilling']
x[cols] = x[cols].apply(LabelEncoder().fit_transform)

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[6,7,8,9,10,11,12,13,14,16])],remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [10]:
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
y[:10]

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 0])

In [12]:
x = pd.DataFrame(x)

In [13]:
x.iloc[:5,:]

0  1  2  3  4  5  6  7  8  9  10  ... 29 30 31 32 33 34  35 36 37     38       39
0  0  1  0  1  0  0  1  0  0  0  0  ...  1  0  0  0  1  0   1  0  1  29.85    29.85
1  1  0  0  1  0  0  0  0  1  1  0  ...  0  1  1  0  0  0  34  1  0  56.95   1889.5
2  1  0  0  1  0  0  0  0  1  0  0  ...  0  1  1  0  0  0   2  1  1  53.85   108.15
3  0  1  0  1  0  0  0  0  1  1  0  ...  0  0  1  0  0  0  45  0  0   42.3  1840.75
4  1  0  0  0  1  0  1  0  0  1  0  ...  1  0  0  0  0  0   2  1  1   70.7   151.65

[5 rows x 40 columns]

In [14]:
cols = x.select_dtypes(exclude=['float']).columns

x[cols] = x[cols].apply(pd.to_numeric, downcast='float', errors='coerce')

In [15]:
x = np.array(x)

**5.Splitting the Data into Training and Test Set**

In [16]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test = tts(x,y,test_size = 0.25,random_state=0)

**6.Feature Scaling**

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
x_train[1,:]

array([ 1.0350713 , -0.32584965, -0.85313404,  1.3815174 , -0.8856972 ,
       -0.5257966 ,  1.0102762 , -0.5257966 , -0.63681614,  1.1299222 ,
       -0.5257966 , -0.7244493 , -0.88910544, -0.5257966 ,  1.3873339 ,
       -0.9962207 , -0.5257966 ,  1.5827118 ,  1.2232004 , -0.5257966 ,
       -0.7875566 , -0.81141776, -0.5257966 ,  1.2601377 , -1.1127155 ,
        1.933189  , -0.5553353 ,  1.8829793 , -0.5225685 , -0.7090153 ,
       -0.54803705,  1.0045542 ,  2.296336  , -0.9694185 , -0.65654284,
        0.8832096 ,  0.32584965, -1.2183915 ,  0.01784008,  0.5549879 ],
      dtype=float32)

In [19]:
y_train[:10]

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0])

In [20]:
y_test[:10]

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0])

**7.Building the Artificial Neural Network and adding Layers**

In [21]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6 , activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6 , activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6 , activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1 , activation = 'sigmoid'))

**8.Compiling and Training ANN**

In [22]:
# We are choosing Stochastic Gradient Descent to Optimize Weights #
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])
# Training Ann by Batch Learning #
ann.fit(x_train,y_train,batch_size=32,epochs = 100)

Epoch 1/100
166/166 [==============================] - 1s 1ms/step - loss: nan - accuracy: 0.6242
Epoch 2/100
166/166 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7329
Epoch 3/100
166/166 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7323
Epoch 4/100
166/166 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7218
Epoch 5/100
166/166 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7235
Epoch 6/100
166/166 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7340
Epoch 7/100
166/166 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7286
Epoch 8/100
166/166 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7329
Epoch 9/100
166/166 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7429
Epoch 10/100
166/166 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7298
Epoch 11/100
166/16

**9.Predicting the Test Set Results**

In [23]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
y_pred[:10]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [24]:
y_test = (y_test > 0.5)
y_pred = y_pred.reshape(len(y_pred),1)
y_test = y_test.reshape(len(y_test),1)
Accuracy_Matrix = np.concatenate((y_pred,y_test),1)
Accuracy_Matrix[:10]

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False,  True],
       [False, False],
       [False, False]])